### ISSUE TITLE
Render issue and CSS positions

### ISSUE THREAD

**Issue by ceiphr** [martinlaxenaire/react-curtains#1]
Hello,

This is a follow up to my comments on https://github.com/martinlaxenaire/curtainsjs/issues/74. 

Good news, the CSS did fix my issue! The effect is being applied to the image. But now that I have it working, I have ~two issues~ one issue I'm struggling to solve.

~For the first issue, I've put an element on top of the curtains image. The element is a card containing text and an image. On hover, the card will translate up by a few pixels and change its box-shadow. When this hover transition occurs in Google Chrome Version 87, the element flickers. This flicker is not present when curtains is disabled.~ Unrelated.

For the second issue, I've tried using curtains with an `absolute` position applied to `.curtains-canvas`. The result is that scrolling causes the image to translate upwards at a faster rate than the scroll. With a `fixed` position, this issue doesn't occur. But, instead the image has a delayed scroll which feels mushy.

The filters I am using can be found on this post:
https://css-tricks.com/animate-images-and-videos-with-curtains-js/

My project is running on Gatsby Version 2.22. You can see the curtains.js image running as the hero banner here: https://dev.ceiphr.com/

~Weird sidenote: Curtains fails to run in my project on Firefox 84. But it's working in Chrome and Firefox Developer Edition (85b). I'm going to investigate this further. I'm assuming it's something I've done with Firefox.~ Unrelated. Fixed.

**Comment by martinlaxenaire** [comment]
Hey @ceiphr,

in this case, you could indeed set the curtains container position to `absolute` and set it `watchScroll` prop to `false`. This should do the trick.

Cheers,

**Comment by ceiphr** [comment]
That worked perfectly, thank you!
