### ISSUE TITLE
Make a plane respect it's parent overflow css value

### ISSUE THREAD

**Issue by laugepetersen** [martinlaxenaire/react-curtains#14]
Hello,

I have cloned the SimpleVideoPlane (https://codesandbox.io/s/react-curtains-simple-video-plane-ckozr) from the Github Docs and was trying to achieve a fullscreen hero-banner with this effect and content following below as a regular website.

Since i want the curtain effect to not show the default body background behind its edges on movement, i tried to enlarge the plane (.SimpleVideoPlane) and make its parent (.hero) overflow value to hidden. This is not working.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/24874516/185208267-223b38b5-bc35-4b55-8832-bad99fcdda98.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/24874516/185207995-d6c8dc39-6f91-40a2-8dcb-1b711abe7588.png">
<img width="231" alt="image" src="https://user-images.githubusercontent.com/24874516/185208064-4fe90141-d378-4549-98f8-a5a53aa25b0a.png">
<img width="178" alt="image" src="https://user-images.githubusercontent.com/24874516/185208110-dd64ed50-dc47-41bc-97c8-1b6ef32fd0c6.png">

**Comment by martinlaxenaire** [comment]
Hey @laugepetersen,

the webgl content is actually rendered in a `<canvas />` element, not inside your `.hero` div.
So this is more a CSS issue, you might want to handle that by tweaking the canvas container `z-index` or `overflow` values for example.
