### ISSUE TITLE
"_interopRequireDefault is not a function" in Examples

### ISSUE THREAD

**Issue by joehuggans** [martinlaxenaire/react-curtains#5]
Hi, thanks for this great repository.

I just want to report that some of the Examples are not currently working, the error I am seeing is "_interopRequireDefault is not a function"

**Comment by martinlaxenaire** [comment]
Hi @joehuggans, 

it seems it had more to do with the way codesandbox is managing packages. After having added the "@babel/runtime" package (see [here](https://stackoverflow.com/questions/66327197/how-to-fix-typeerror-interoprequiredefault-is-not-a-function-in-create-react-ap)) to all the examples they seem to be working fine again.

Thanks for pointing that out tho.

Cheers,

**Comment by joehuggans** [comment]
Awesome, thanks.
